# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  # Les variables suivantes doivent déjà être définies dans ton dashboard Netlify
  # VITE_SUPABASE_URL
  # VITE_SUPABASE_ANON_KEY

# Cache control: on évite de cacher index.html mais on maximise pour les assets
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirection SPA: toutes les routes renvoient vers index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
