[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_FLAGS = "--no-audit --no-fund --prefer-offline"

# No-cache pour la page d'entrée (évite Ctrl+Shift+R)
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache long uniquement pour les assets fingerprintés Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
